name: bare-with-bash
version: "1.0"
summary: Empty base snap for snaps that need no libc or similar.
description: |
    An empty base snap that contains nothing except the directories
    required as mount points.
architectures:
  - all
base: bare
build-base: core18
grade: stable
confinement: strict

parts:
  dir-layout:
    plugin: make
    source: .